apiVersion: v1
kind: Service
metadata:
  labels:
    app: restapi
    deployed: ${TF_VAR_project}
  name: restapi
spec:
  ports:
    - name: "5000"
      port: 5000
      targetPort: 5000
  selector:
    app: restapi
status: {}

